sudo: required
language: python
python:
  - "3.6"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq tar python3 bzip2 build-essential
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
  - bash ~/miniconda.sh -b -p /home/travis/miniconda
  - /home/travis/miniconda/bin/conda config --set always_yes yes --set changeps1 no
  - /home/travis/miniconda/bin/conda update -q conda
  - /home/travis/miniconda/bin/conda info -a
  - /home/travis/miniconda/bin/conda install scipy numpy pandas
  - /home/travis/miniconda/bin/conda install -c biocore mafft psipred=4.01
  - /home/travis/miniconda/bin/pip install --upgrade
  - /home/travis/miniconda/bin/pip install py pytest pytest-xdist pytest-cov pytest-colordots
  - /home/travis/miniconda/bin/pip install biopython statsmodels python-coveralls buddysuite
  - touch /home/travis/build/biologyguy/RD-MCL/rdmcl/config.ini
  - mkdir /home/travis/build/biologyguy/RD-MCL/rdmcl/psipred/
  - cp -r /home/travis/miniconda/share/psipred_4.01/data /home/travis/build/biologyguy/RD-MCL/rdmcl/psipred/
script:
  - source test.sh