sudo: required
language: python
python:
  - "3.6"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq tar python3 bzip2 build-essential
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
  - bash ~/miniconda.sh -b -p /home/travis/miniconda
  - /home/travis/miniconda/bin/conda config --set always_yes yes --set changeps1 no
  - /home/travis/miniconda/bin/conda update -q conda
  - /home/travis/miniconda/bin/conda info -a
  - /home/travis/miniconda/bin/conda install scipy numpy pandas git
  - /home/travis/miniconda/bin/conda install -c biocore mafft psipred=4.01
  - /home/travis/miniconda/bin/conda install -c bioconda clustalo
  - /home/travis/miniconda/bin/pip install --upgrade
  - /home/travis/miniconda/bin/pip install py pytest pytest-xdist pytest-cov pytest-colordots
  - /home/travis/miniconda/bin/pip install biopython python-coveralls buddysuite dill
  - /home/travis/miniconda/bin/git clone https://github.com/biologyguy/BuddySuite.git /home/travis/build/biologyguy/BuddySuite
  - /home/travis/miniconda/bin/git --git-dir=/home/travis/build/biologyguy/BuddySuite/.git --work-tree=/home/travis/build/biologyguy/BuddySuite checkout develop
  - mv /home/travis/build/biologyguy/BuddySuite/buddysuite/*.py /home/travis/miniconda/lib/python3.6/site-packages/buddysuite/
  - touch /home/travis/build/biologyguy/RD-MCL/rdmcl/config.ini
  - mkdir /home/travis/build/biologyguy/RD-MCL/rdmcl/psipred/
  - cp -r /home/travis/miniconda/share/psipred_4.01/data /home/travis/build/biologyguy/RD-MCL/rdmcl/psipred/
  - wget -q http://eddylab.org/software/hmmer3/3.1b2/hmmer-3.1b2.tar.gz -O ~/hmmer-3.1b2.tar.gz
  - tar -xzf ~/hmmer-3.1b2.tar.gz -C ~/
  - sed -i -e 's/p7_gmx_Dump(stdout, fwd, p7_DEFAULT);//g' ~/hmmer-3.1b2/src/generic_fwdback.c
  - (cd ~/hmmer-3.1b2 && ./configure && make)
  - mv ~/hmmer-3.1b2/src/hmmbuild /home/travis/miniconda/bin/hmmbuild
  - (cd ~/hmmer-3.1b2/src && make generic_fwdback_example)
  - mkdir /home/travis/build/biologyguy/RD-MCL/rdmcl/hmmer
  - cp ~/hmmer-3.1b2/src/generic_fwdback_example /home/travis/build/biologyguy/RD-MCL/rdmcl/hmmer/hmm_fwd_back
  - cp ~/hmmer-3.1b2/src/generic_fwdback_example /home/travis/miniconda/bin/hmm_fwd_back
script:
  - travis_wait 40 source test.sh