sudo: required
language: python
python:
  - "3.6"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq tar python3 bzip2 build-essential
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
  - bash ~/miniconda.sh -b -p /home/travis/miniconda
  - /home/travis/miniconda/bin/conda config --set always_yes yes --set changeps1 no
  - /home/travis/miniconda/bin/conda config --add channels r
  - /home/travis/miniconda/bin/conda config --add channels bioconda
  - /home/travis/miniconda/bin/conda update -q conda
  - /home/travis/miniconda/bin/conda info -a
  - /home/travis/miniconda/bin/conda install scipy numpy pandas mafft
  - /home/travis/miniconda/bin/pip install --upgrade
  - /home/travis/miniconda/bin/pip install py pytest pytest-xdist pytest-cov pytest-colordots biopython statsmodels
  - /home/travis/miniconda/bin/pip install python-coveralls buddysuite
  - git clone -b develop https://github.com/biologyguy/BuddySuite.git /home/travis/BuddySuite
  - mv /home/travis/BuddySuite/buddysuite/buddy_resources.py /home/travis/miniconda/lib/python3.6/site-packages/buddysuite/
  - wget -q http://bioinfadmin.cs.ucl.ac.uk/downloads/psipred/old_versions/psipred.4.0.tar.gz -O ~/psipred.tgz
  - tar -xzf ~/psipred.tgz --directory ~/
  - make -C ~/psipred/src
  - mv ~/psipred/src/chkparse ~/psipred/src/psipass2 ~/psipred/src/psipred ~/psipred/src/seq2mtx /home/travis/build/biologyguy/RD-MCL/rdmcl/psipred/bin/
script:
  - source test.sh